# Generated by Django 5.2 on 2025-05-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='apellido_nombre',
            new_name='apellido_y_nombre',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='important',
            new_name='importante',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='turno',
        ),
    ]
