# Generated by Django 5.2 on 2025-05-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_apellido_nombre_task_apellido_y_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterField(
            model_name='task',
            name='especialidad',
            field=models.CharField(choices=[('CHOFER_LIVIANA', 'Chofer Liviana'), ('CHOFER_PESADA', 'Chofer Pesada'), ('OPERADOR', 'Operador'), ('AUXILIAR', 'Auxiliar'), ('BUZO_DE_BORDA', 'Buzo de Borda'), ('BUZO_DEPORTIVO', 'Buzo Deportivo'), ('CONDUCTOR_NAUTICO', 'Conductor Náutico'), ('TIMONEL', 'Timonel'), ('ELECTRICISTA', 'Electricista'), ('FURRIEL', 'Furriel'), ('NADADOR_DE_RESCATE', 'Nadador de Rescate'), ('GUARDAVIDA', 'Guardavida')], default='OPERADOR', max_length=100, verbose_name='Especialidad del Personal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='jerarquia',
            field=models.CharField(choices=[('BOMBERO_CALIFICADO', 'Bombero Calificado'), ('BOMBERO_SUPERIOR', 'Bombero Superior'), ('SUBTENIENTE', 'Subteniente'), ('TENIENTE', 'Teniente'), ('CAPITAN', 'Capitán')], default='BOMBERO_CALIFICADO', max_length=100, verbose_name='Jerarquía del Personal'),
        ),
    ]
