# Generated by Django 5.2 on 2025-05-28 04:46

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options_alter_task_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='especialidad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CHOFER_LIVIANA', 'Chofer Liviana'), ('CHOFER_PESADA', 'Chofer Pesada'), ('BUZO_DE_BORDA', 'Buzo de Borda'), ('BUZO_DEPORTIVO', 'Buzo Deportivo'), ('CONDUCTOR_NAUTICO', 'Conductor Náutico'), ('TIMONEL', 'Timonel'), ('ELECTRICISTA', 'Electricista'), ('FURRIEL', 'Furriel'), ('NADADOR_DE_RESCATE', 'Nadador de Rescate'), ('GUARDAVIDA', 'Guardavida')], max_length=200, null=True, verbose_name='Especialidades del Personal'),
        ),
        migrations.AlterField(
            model_name='task',
            name='jerarquia',
            field=models.CharField(choices=[('BOMBERO_CALIFICADO', 'Bombero Calificado'), ('BOMBERO_SUPERIOR', 'Bombero Superior'), ('SUBTENIENTE', 'Subteniente'), ('TENIENTE', 'Teniente'), ('CAPITAN', 'Capitán')], max_length=100, verbose_name='Jerarquía'),
        ),
    ]
